/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 5be42eb2a2053725795d5fa55db9b8d7)
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "ForeverChatAgent";
  }
  interface Env {
    AI: Ai;
    ForeverChatAgent: DurableObjectNamespace<
      import("./src/server").ForeverChatAgent
    >;
  }
}
interface Env extends Cloudflare.Env {}
